### PR TITLE
Fix name in charter.md

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by crosbymichael** [comment]
We will have to change the spelling in the official document for the charter.

**Comment by LK4D4** [comment]
I wonder if it's possible, ping @chanezon 
I can live with this if it's too hard.

**Comment by wking** [comment]
On Mon, Oct 05, 2015 at 11:33:18AM -0700, Michael Crosby wrote:
> We will have to change the spelling in the official document for the
> charter.

The accepted charter [1] ended up going with a link to a MAINTAINERS
file (currently using the obsolete opencontainers/specs name for
runtime-specs and not quite spelling out how this works with multiple
projects).  So this name-typo fix is obsolete, and this PR can be
closed.

[1]: https://www.opencontainers.org/about/governance

**Comment by LK4D4** [comment]
ping @crosbymichael

**Comment by crosbymichael** [comment]
LGTM

ping @caniszczyk for merge

**Comment by wking** [comment]
> ping @caniszczyk for merge

Wait, what?  The line this is PR fixing is not in the adopted charter.  Why bother landing a PR to fix the stale provisional charter in this repo?

**Comment by caniszczyk** [comment]
This repo isn't active anymore, the website isn't on GitHub:
https://www.opencontainers.org/

I've updated the repo description to mentioned it's archived and inactive.

**Pull request closed without merging**
